name: CI/CD - Build and Deploy to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 (recommended)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Updated to v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3  # Updated to v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # Build context is repository root
        file: ./Dockerfile  # Explicit path to Dockerfile
        push: true
        tags: bblue96/my-node-app:latest
